### ISSUE TITLE
Unable to resolve import path - How to solve this?

### ISSUE THREAD

**Issue by sjamayee** [nexusdev/demo#1]
Don't know how to solve this.
I get this everywhere (feedbase, the-tao, ...) with import of dappsys

iMac:dapple_demo jac$ dapple test
Testing...
Error: Unable to resolve import path 'erc20/erc20.sol' in file '/Users/jac/_GIT/dapple_demo/contracts/test.sol'
    at Function.resolveImport (/usr/local/lib/node_modules/dapple/lib/linker.js:47:11)
    at linked.(anonymous function).source.replace (/usr/local/lib/node_modules/dapple/lib/linker.js:83:35)
    at RegExp.[Symbol.replace](native)
    at String.replace (native)
    at Function.linkImports (/usr/local/lib/node_modules/dapple/lib/linker.js:81:33)
    at Function.link (/usr/local/lib/node_modules/dapple/lib/linker.js:14:36)
    at DestroyableTransform._flush (/usr/local/lib/node_modules/dapple/lib/streams/linker.js:19:32)
    at DestroyableTransform.<anonymous> (/usr/local/lib/node_modules/dapple/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:286:16)
    at emitNone (events.js:86:13)

**Must have something todo with this (solidity):
To import a file x from the same directory as the current file, use import "./x" as x;.
If you use import "x" as x; instead, a different file could be referenced (in a global “include directory”).**

**Comment by nmushegian** [comment]
are you initializing submodules?

`git submodule --init --recursive update`

**Comment by nmushegian** [comment]
If that fixes it, then the real issue is that those are not detected by dapple..

**Comment by sjamayee** [comment]
Yes, now it's OK.

iMac:dapple_demo jac$ git submodule init
Submodule 'dapple_packages/erc20' (https://github.com/nexusdev/erc20) registered for path 
'dapple_packages/erc20'

iMac:dapple_demo jac$ git submodule update --recursive
Cloning into 'dapple_packages/erc20'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 12 (delta 0), reused 12 (delta 0), pack-reused 0
Unpacking objects: 100% (12/12), done.
Checking connectivity... done.
Submodule path 'dapple_packages/erc20': checked out 'c0b1dfcba80f4fcd61eebc0708203a1e6d8a8478'

iMac:dapple_demo jac$ dapple test
Testing...
Using local solc installation...

DemoTest
  test fail non admin set balance
  Passed!

  test can transfer to whitelisted
  Passed!

  test component manager grant root
  Passed!

  test set balance
  Passed!

  test fail cant transfer to un whitelisted
  Failed!

Failing Tests
  DemoTest: test fail cant transfer to un whitelisted

Summary
  Failed 1 out of 5 tests.
